apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo-img
          image: marmotas/devopsdemo@sha256:sha0to0be0replaced
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
spec:
  selector:
    app: devops-demo
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-demo-ingress
  annotations:
    kubernetes.io/ingress.class: web
spec:
  rules:
    - host: dev.niclaslamponen.com
      http:
        paths:
        - backend:
            serviceName: devops-demo-service
            servicePort: 80
