---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo-img
          image: marmotas/devopsdemo@sha256:abcd
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
spec:
  selector:
    app: devops-demo
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-demo-ingress
  # annotations:
          # kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: dev.niclaslamponen.com
      http:
        paths:
        - backend:
            serviceName: devops-demo-service
            servicePort: 80
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: devops-demo-ingress
#  annotations:
#    kubernetes.io/ingress.class: "traefik"
#    cert-manager.io/cluster-issuer: letsencrypt-prod
#spec:
#  rules:
#    - host: dev.niclaslamponen.com
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: devops-demo-service
#              servicePort: http
#  tls:
#  - hosts:
#    - dev.niclaslamponen.com
#    secretName: dev-niclaslamponen-com-tls
#---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: devops-demo-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
#    - host: dev.niclaslamponen.com
#      http:
#        paths:
#        - backend:
#            serviceName: devops-demo-service
#            servicePort: 80
# - http:
#     paths:
#     - path: /
#       pathType: Prefix
#       backend:
#         service:
#           name: devops-demo-service
#           port:
#             number: 80
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  namespace: metallb-system
#  name: config
#data:
#  config: |
#    address-pools:
#    - name: default
#      protocol: layer2
#      addresses:
#      - 95.217.186.152/1
