additionalArguments:
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le.acme.email=niclas.lamponen@outlook.com"
  - "--certificatesresolvers.le.acme.tlschallenge=true"

persistence:
  enabled: true
  path: /data

service:
  enabled: true
  type: NodePort
  externalIPs:
  - "95.217.186.152"
