apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-persistence
  namespace: traefik
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volumes/traefik"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-persistence
  namespace: traefik
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

